<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Tz7e1n\App_ChoosyBundleKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Tz7e1n/App_ChoosyBundleKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container4Tz7e1n.legacy');

    return;
}

if (!\class_exists(App_ChoosyBundleKernelTestDebugContainer::class, false)) {
    \class_alias(\Container4Tz7e1n\App_ChoosyBundleKernelTestDebugContainer::class, App_ChoosyBundleKernelTestDebugContainer::class, false);
}

return new \Container4Tz7e1n\App_ChoosyBundleKernelTestDebugContainer([
    'container.build_hash' => '4Tz7e1n',
    'container.build_id' => 'c97814dc',
    'container.build_time' => 1672913886,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Tz7e1n');
