<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYXEaqaM\App_ChoosyBundleKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYXEaqaM/App_ChoosyBundleKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYXEaqaM.legacy');

    return;
}

if (!\class_exists(App_ChoosyBundleKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYXEaqaM\App_ChoosyBundleKernelTestDebugContainer::class, App_ChoosyBundleKernelTestDebugContainer::class, false);
}

return new \ContainerYXEaqaM\App_ChoosyBundleKernelTestDebugContainer([
    'container.build_hash' => 'YXEaqaM',
    'container.build_id' => 'd899e3c7',
    'container.build_time' => 1673276490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYXEaqaM');
