<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtweal6\App_ChoosyBundleKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtweal6/App_ChoosyBundleKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPtweal6.legacy');

    return;
}

if (!\class_exists(App_ChoosyBundleKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPtweal6\App_ChoosyBundleKernelTestDebugContainer::class, App_ChoosyBundleKernelTestDebugContainer::class, false);
}

return new \ContainerPtweal6\App_ChoosyBundleKernelTestDebugContainer([
    'container.build_hash' => 'Ptweal6',
    'container.build_id' => '36a077d8',
    'container.build_time' => 1675130302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtweal6');
