<?php

namespace ContainerX7Qq1D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TxxB1FtService extends App_ChoosyBundleKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.TxxB1Ft' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TxxB1Ft'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'environment' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'environment' => '?',
        ]);
    }
}
