<?php

namespace ContainerX7Qq1D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestControllerService extends App_ChoosyBundleKernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\TestController' shared autowired service.
     *
     * @return \App\Controller\TestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TestController.php';

        $container->services['App\\Controller\\TestController'] = $instance = new \App\Controller\TestController();

        $instance->setContainer($container);

        return $instance;
    }
}
