name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.0
          - 8.1
    steps:
    - uses: actions/checkout@v3
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install assets
        yarn --cwd ./src/Resources/assets install --force
        yarn --cwd ./tests/app install --force
    - name: Compile assets
        yarn --cwd ./src/Resources/assets  dev
        yarn --cwd ./tests/app dev
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --configuration ./phpunit.xml.dist
